language: node_js
node_js:
  - 10
install: yarn --ignore-engines # ignore engines to test node 6, otherwise it fails on engine check
cache: yarn
jobs:
  include:
    - stage: Verify
      name: Travis Status
      script: yarn travis-github-status
    - # stage name not required, will continue to use `Build`
      name: ESlint
      script: npm run lint
    - stage: Release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
